# Generated by Django 4.0.4 on 2022-04-30 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingrediend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingrediend',
            new_name='Ingredient',
        ),
    ]
